# comment for diff
dist: trusty

language: node_js
node_js: 
 - 10.10.0

services:
  - redis-server

addons:
  apt:
    packages:
      - xsel

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set cache-folder $HOME/.cache/yarn

stages:
  - test

before_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; 
sleep 3; fi'
  - sudo redis-server /etc/redis/redis.conf --port 6379

jobs:
  include:
    - stage: test
      script: yarn lint && yarn depcheck && lerna bootstrap && yarn test:ci && curl -s https://codecov.io/bash | bash

cache:
  yarn: true
  directories:
    - $HOME/.nvm/.cache
    - $HOME/.cache/yarn
    - node_modules
    - packages/**/node_modules

git:
  depth: 1

