dist: trusty

language: node_js
node_js: 
 - 10.10.0

services:
  - redis-server
  - sqlite3

addons:
  apt:
    packages:
      - xsel

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set cache-folder $HOME/.cache/yarn
  - sudo apt-get update -q
  - sudo apt-get install -q sqlite3
  - sudo service sqlite3 restart

install: yarn

stages:
  - test
  - lint
  - depcheck

before_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; 
sleep 3; fi'
  - sudo redis-server /etc/redis/redis.conf --port 6379

script:
  - yarn test:force-exit --ci --coverage
  - codecov

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: depcheck
      script: yarn depcheck

cache:
  yarn: true
  directories:
    - $HOME/.nvm/.cache
    - $HOME/.cache/yarn
    - node_modules
    - packages/**/node_modules

git:
  depth: 1

